### PR TITLE
Revert to v2.8.3

### PR DESCRIPTION
**Pull request by ritumd**
## Checklist before submitting

- [X] Did you read the [contributor guide](https://github.com/open-ce/open-ce/blob/main/CONTRIBUTING.md)?
- [ ] Did you update any affected [documentation](https://github.com/open-ce/open-ce/blob/main/doc/)?
- [ ] Did you write any tests to validate this change?

## Description

Fixes # (issue).

## Review process to land 

1. All tests and other checks must succeed.
2. At least one [maintainer](https://github.com/open-ce/open-ce/blob/main/MAINTAINERS.md) must review and approve.
3. If any  [maintainer](https://github.com/open-ce/open-ce/blob/main/MAINTAINERS.md) requests changes, they must be addressed.

### CODE REVIEW

**Comment by alexlang74** [comment]
This is reverted because it creates problems with Tensorflow, correct? You may want to add a comment into the file to track that...

**Review by alexlang74 — APPROVED** [review]

**Comment by cdeepali** [comment]
This is reverted because all packages on main are presently built & tested with NCCL v2.8.3. 
(We happen to merge PR NCCL 2.11 early.) We will put v2.11 again when we merge other PRs for OpenCE 1.5.

**Comment by cdeepali** [comment]
I think a correction is needed here. @ritumd we do not see any thing in the Files changed as of now?

**Comment by ritumd** [comment]
> This is reverted because it creates problems with Tensorflow, correct? You may want to add a comment into the file to track that...

**Pull request closed without merging**
